// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqKk3e7YzakTJmhWaCsXuP9qxtAY8jTLE',
    appId: '1:351613245539:web:f9d1f57f1d1bd33b814056',
    messagingSenderId: '351613245539',
    projectId: 'cocofapp',
    authDomain: 'cocofapp.firebaseapp.com',
    databaseURL: 'https://cocofapp-default-rtdb.firebaseio.com',
    storageBucket: 'cocofapp.appspot.com',
    measurementId: 'G-3WVEKGYFVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe32JSClSk-oJWVZxbThi9in04gTN7W9c',
    appId: '1:351613245539:android:9706c391d464b45a814056',
    messagingSenderId: '351613245539',
    projectId: 'cocofapp',
    databaseURL: 'https://cocofapp-default-rtdb.firebaseio.com',
    storageBucket: 'cocofapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0rv96SygveSLUJmwAXCcDzJerhnSY5zU',
    appId: '1:351613245539:ios:b0a8a7338f6c9933814056',
    messagingSenderId: '351613245539',
    projectId: 'cocofapp',
    databaseURL: 'https://cocofapp-default-rtdb.firebaseio.com',
    storageBucket: 'cocofapp.appspot.com',
    iosBundleId: 'com.example.cocofapp',
  );
}
